<a href="https://colab.research.google.com/github/sancarhacer/DataSciencewithPython/blob/main/1_IntroToNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# !pip install numpy


In [ ]:
my_list = [10,20,30,40]
type(my_list)

list

In [ ]:
# array listlere göre daha katı kuralları olaur mesela kapasitesi değişmez numpy array normal arrayden daha farklıdır
np.array(my_list)

array([10, 20, 30, 40])

In [ ]:
my_numpy_array = np.array([10,20,30,40,50])
type(my_numpy_array)

numpy.ndarray

In [ ]:
my_numpy_array.max()

np.int64(50)

In [ ]:
# https://jalammar.github.io/visual-numpy/
#Uzunluğu 5 olan, tüm elemanları $1.0$ olan bir NumPy dizisi (vektör) oluşturur.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
#array arithmetic
my_list1 = [1,2]
my_list2 = [2,3]
my_list1 + my_list2
[1, 2, 2, 3]

[1, 2, 2, 3]

In [ ]:
my_numpy_array1 = np.array(my_list1)
my_numpy_array2 = np.array(my_list2)
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [ ]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [ ]:
my_numpy_array1*- my_numpy_array2

array([-2, -6])

In [ ]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [ ]:
other_array = np.array([10,20,30,40,50])
other_array.min()


np.int64(10)

In [ ]:
other_array.sum()

np.int64(150)

Broadcasting: iki arrayi birbiriyle çarparken ya aynı boyutta olmalılar ya da biri tek boyut olmalı

In [ ]:
# aşağıdaki gibi hata olur yoksa
# array1 = np.array([1,2,3,4,5])
# array2 = np.array([6,7])
# array1 * array2

In [ ]:
#indexing & arange
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np_array = np.arange(0,10)
np_array[0]

np.int64(0)

In [ ]:
np_array[-1]

np.int64(9)

In [ ]:
np_array[1:4:]

array([1, 2, 3])

In [ ]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
np_array[2:6:2]

array([2, 4])

In [ ]:
# random
np.random.randn(4)

array([1.16550647, 0.85853585, 0.17989071, 0.41791113])

In [ ]:
#  Uzunluğu 6 olan, tüm elemanları $0.0$ ile $1.0$ arasında rastgele seçilmiş ondalıklı sayılar ($float$) olan bir NumPy dizisi (vektör) oluşturur.
# İki boyutlu bir dizi (örneğin $2 \times 3$ matris) oluşturmak için: np.random.
# Belirtilen aralıktaki her sayının çekilme olasılığı eşittir.Dağılım	Üniform (Tekdüze).
# random((2, 3))
np.random.random(6)

array([0.10505825, 0.61690248, 0.78309777, 0.41058187, 0.8589074 ,
       0.52721736])

In [ ]:
# DağılımStandart Normal (Gauss).
# ParametrelerOrtalama ortalam = 0 ve Standart Sapma sigma = 1'dir.
# üretilen sayılar eşit olasılığa sahip değildir.
# Bunun nedeni, bu fonksiyonun sayıları Standart Normal Dağılım'dan (Standard Normal Distribution) çekmesidir.
# Gerçek verileri taklit eden, ancak gizlilik gerektiren durumlarda, normal dağılımlı sentetik test verileri oluşturmak için kullanılır.
# Sinir ağlarındaki ağırlık (weights) matrislerini başlatmak için yaygın olarak kullanılır.
# 0'a yakın değerlerle başlamak, eğitimin daha istikrarlı olmasına yardımcı olabilir.
np.random.randn(4,4) #we will see matrices in details

array([[ 0.09608777, -1.21719754,  0.46252957,  1.15366035],
       [-1.51302346,  1.4994308 , -0.80683346,  0.09576535],
       [ 1.30775202, -0.2130547 , -0.30086242, -0.30792517],
       [-0.58508963,  0.62554845,  1.12920938, -0.06028829]])

In [ ]:
np.random.randint(1,300,5)

array([246, 276, 219,  66, 268])