<a href="https://colab.research.google.com/github/sancarhacer/DataSciencewithPython/blob/main/3_NumpyOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
new_array = np.random.randint(1,100,20)
new_array

array([81,  1, 42, 23, 18, 66, 31, 24, 97, 46, 14, 20, 35, 55,  7, 42, 38,
       42,  4, 18])

In [ ]:
new_array >25

array([ True, False,  True, False, False,  True,  True, False,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
       False, False])

In [ ]:
new_array[new_array > 25]

array([81, 42, 66, 31, 97, 46, 35, 55, 42, 38, 42])

In [ ]:
#transpose & reshape

In [ ]:
matrix_array = np.array([[10,20],[20,30],[30,40]])
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [ ]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [ ]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [ ]:
random_array = np.random.random((6,1))
random_array

array([[0.93943791],
       [0.95725079],
       [0.80935847],
       [0.41287476],
       [0.20621673],
       [0.56230958]])

In [ ]:
random_array.reshape(3,2)

array([[0.93943791, 0.95725079],
       [0.80935847, 0.41287476],
       [0.20621673, 0.56230958]])

In [ ]:
# real life cases
data = np.array([10, 12, 13, 15, 18, 25, 100, 105])
# Compute Z-scores
mean = np.mean(data)
std = np.std(data)
z_scores = (data - mean) / std
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [ ]:
np.abs(z_scores) > 1

array([False, False, False, False, False, False,  True,  True])

In [ ]:
outliers = data[np.abs(z_scores)>1]
outliers

array([100, 105])

In [ ]:
# math equations
# Solve 2x + 3y = 8 and 5x + 7y = 19
# Coefficients matrix
A = np.array([[2, 3], [5, 7]])
# Constants matrix
b = np.array([8, 19])
# Solve for x and y
solution = np.linalg.solve(A, b)
solution

array([1., 2.])

In [ ]:
# data analysis
# Stock prices over 5 days
prices = np.array([100, 102, 105, 107, 110])
np.diff(prices)
# np.diff() fonksiyonu, bir dizideki (array) ardışık elementler arasındaki farkı hesaplayarak yeni bir dizi oluşturur.

array([2, 3, 2, 3])

In [ ]:
prices[:len(prices)-1:]

array([100, 102, 105, 107])

In [ ]:
prices[:-1:]

array([100, 102, 105, 107])

In [ ]:
prices[:-1]

array([100, 102, 105, 107])

In [ ]:
np.diff(prices) / prices[:-1]
#  mutlak olarak ne kadar değiştiğini (örneğin $2$ TL arttı) değil, yüzde olarak ne kadar değiştiğini (örneğin %2 arttı) görmek için yapılır.

array([0.02      , 0.02941176, 0.01904762, 0.02803738])

In [ ]:
returns = np.diff(prices) / prices[:-1] * 100
returns

array([2.        , 2.94117647, 1.9047619 , 2.80373832])